[[source]]
url = "https://github.com/mattpocock/skills/tree/main/skills/productivity"
skills = ["grill-me", "caveman", "handoff", "write-a-skill"]

[[source]]
url = "https://github.com/mattpocock/skills/tree/main/skills/engineering"
skills = ["diagnose", "grill-with-docs", "improve-codebase-architecture", "prototype", "setup-matt-pocock-skills", "tdd", "to-issues", "to-prd", "triage", "zoom-out"]
